version: '3.8'
services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookkeeping_backend_development
    ports:
      - "5432:5432"

volumes:
  postgres_data:
