version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bookkeeping
      - POSTGRES_USER=bookkeeper
      - POSTGRES_PASSWORD=bookpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookkeeper -d bookkeeping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: