# Generated by Django 5.2 on 2025-04-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_description', models.TextField(blank=True, help_text='Description substring to match (case insensitive)', null=True)),
                ('filter_amount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Amount value to compare', max_digits=12, null=True)),
                ('filter_amount_comparison', models.CharField(blank=True, choices=[('above', 'Above'), ('below', 'Below'), ('equal', 'Equal')], help_text='Amount comparison operator', max_length=10, null=True)),
                ('category', models.TextField(blank=True, help_text='Category to set when rule matches', null=True)),
                ('flag_message', models.TextField(blank=True, help_text='Flag message to add when rule matches', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='transaction_created_42bc59_idx')],
            },
        ),
    ]
