# Generated by Django 5.2 on 2025-04-09 03:42

from django.db import migrations
from decimal import Decimal

def add_default_rules(apps, schema_editor):
    """
    Add default transaction rules that are applied automatically.
    """
    # Get the model from the versioned app registry
    TransactionRule = apps.get_model('transactions', 'TransactionRule')
    
    # Grocery Auto-categorization
    TransactionRule.objects.create(
        filter_description='grocery',
        category='Groceries',
    )
    
    # Restaurant Auto-categorization
    TransactionRule.objects.create(
        filter_description='restaurant',
        category='Dining',
    )
    
    # Gas/Fuel Auto-categorization
    TransactionRule.objects.create(
        filter_description='gas',
        category='Transportation',
    )
    
    # High Amount Rule
    TransactionRule.objects.create(
        filter_amount_value=Decimal('1000.00'),
        filter_amount_comparison='above',
        flag_message='High value transaction (>$1,000)',
    )

    # Negative Amount Rule (Income)
    TransactionRule.objects.create(
        filter_amount_comparison='below',
        filter_amount_value=Decimal('0.00'),
        category='Income',
    )

def remove_default_rules(apps, schema_editor):
    """
    Remove default rules when migrating backwards.
    """
    TransactionRule = apps.get_model('transactions', 'TransactionRule')
    # Delete all rules created by this migration
    TransactionRule.objects.filter(flag_message__startswith='Auto-categorized').delete()
    TransactionRule.objects.filter(flag_message='High value transaction (>$1,000)').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactionrule'),
    ]

    operations = [
        migrations.RunPython(add_default_rules, remove_default_rules),
    ]
