# Generated by Django 5.2 on 2025-04-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_add_default_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionflag',
            name='is_resolvable',
            field=models.BooleanField(default=False, help_text='Whether this flag can be manually resolved by the user'),
        ),
    ]
