# Generated by Django 5.2 on 2025-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transactionflag_is_resolvable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionflag',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='transactionflag',
            index=models.Index(fields=['transaction', 'flag_type'], name='transaction_transac_d355e3_idx'),
        ),
    ]
