# Generated by Django 5.2 on 2025-04-12 00:12

from django.db import migrations, models


def convert_old_rules_to_new_format(apps, schema_editor):
    """
    Convert old rules format to new JSONField format.
    """
    TransactionRule = apps.get_model('transactions', 'TransactionRule')
    
    # Get all existing rules
    for rule in TransactionRule.objects.all():
        filter_condition = {}
        
        # Convert description filter
        if hasattr(rule, 'filter_description') and rule.filter_description:
            filter_condition['description__icontains'] = rule.filter_description
            
        # Convert amount filter
        if hasattr(rule, 'filter_amount_value') and rule.filter_amount_value is not None and hasattr(rule, 'filter_amount_comparison') and rule.filter_amount_comparison:
            if rule.filter_amount_comparison == 'above':
                filter_condition['amount__gt'] = float(rule.filter_amount_value)
            elif rule.filter_amount_comparison == 'below':
                filter_condition['amount__lt'] = float(rule.filter_amount_value)
            elif rule.filter_amount_comparison == 'equal':
                filter_condition['amount'] = float(rule.filter_amount_value)
        
        # Update rule with new filter_condition
        rule.filter_condition = filter_condition
        rule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_transaction_amount_94b800_idx'),
    ]

    operations = [
        # Add the new JSONField first
        migrations.AddField(
            model_name='transactionrule',
            name='filter_condition',
            field=models.JSONField(blank=True, default=dict, help_text="JSON filter condition (e.g., {'amount__gt': 100, 'description__icontains': 'coffee'})", null=True),
        ),
        
        # Convert old rules to new format
        migrations.RunPython(convert_old_rules_to_new_format),
        
        # Remove old fields
        migrations.RemoveField(
            model_name='transactionrule',
            name='filter_amount_comparison',
        ),
        migrations.RemoveField(
            model_name='transactionrule',
            name='filter_amount_value',
        ),
        migrations.RemoveField(
            model_name='transactionrule',
            name='filter_description',
        ),
    ]
