# Generated by Django 5.2 on 2025-04-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_add_default_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionflag',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Whether this flag has been manually resolved by the user'),
        ),
        migrations.AddIndex(
            model_name='transactionflag',
            index=models.Index(fields=['is_resolved'], name='transaction_is_reso_f1477c_idx'),
        ),
    ]
