# Generated by Django 5.2 on 2025-04-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_add_is_resolved_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_amount_94b800_idx',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['amount', 'description', 'datetime'], name='transaction_amount_4bdaa8_idx'),
        ),
    ]
